[target.xtensa-esp32s2-none-elf]
runner = "espflash flash --monitor --chip esp32s2 --partition-table partition_table.csv"

[env]

[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
]

target = "xtensa-esp32s2-none-elf"

[unstable]
build-std = ["alloc", "core"]
